title: Science & Us
# tagline and description for meta tags
tagline: Making the complex compelling
description: Student-led organization that teaches high school students about science communication and interdisciplinary careers in STEM, through biannual events, a starter kit for clubs, and more.
url: https://scienceandus.org # no slash means that all relative URLs that prepend site.url must begin with a slash

permalink: /:title # clean URLs, e.g. /about as opposed to /about.html

# notes:
# - order of links in this file determines order on website
# - all relative URLs should be appended to site.url, regardless of source file directory

# homepage links
links:
  - name: About
    url: /about
  - name: Conference
    url: /conference
  - name: Starter Kit
    url: /kit
  - name: Collaborate
    url: /collaborate
  - name: Blog
    url: /blog

# homepage images

# social media
social_media:
  - name: Facebook
    url: http://facebook.com/sciandus
    icon_url: /icons/facebook-logo.svg

# organizers
team:
  - name: Katherine Huang
  - name: Angela Tran
  - name: Shreyaa Raghavan
  - name: Parin Shaik
  - name: Kumi Devalla
  - name: Sasha Hussain

# sponsors
sponsors:
  - name: Upstatement
    link: http://upstatement.com
    logo_relative_url: /upstatement.png
  - name: Balsamiq
    link: http://balsamiq.com
    logo_relative_url: /balsamiq.png
  - name: MIT Beaver Works Summer Institute
    link: https://beaverworks.ll.mit.edu/CMS/bw/
    logo_relative_url: /beaverworks.png
  - name: Ultrapress
    link: http://Ultrapress.com
    logo_relative_url: /ultrapress.png
  - name: Gunnar
    link: http://gunnar.com
    logo_relative_url: /gunnar.png
  - name: Accion
    link: http://accion-systems.com
    logo_relative_url: /accion.png
  - name: DataCamp
    link: http://datacamp.com
    logo_relative_url: /datacamp.png
  - name: Commonwealth Institute
    link: http://commonwealthinstitute.org/
    logo_relative_url: /commonwealthinstitute.png
  - name: intellADAPT
    link: http://intelladapt.com/
    logo_relative_url: /intelladapt.png
  - name: National Center for Women & IT
    link: http://ncwit.org/
    logo_relative_url: /ncwit.jpg
  - name: Hacking Pediatrics
    link: http://hackingpediatrics.health/
    logo_relative_url: /hackingpediatrics.JPG
  - name: Quarter Zero
    link: http://quarterzero.com/
    logo_relative_url: /quarterzero.jpg
  - name: Harvard Student Agencies Summer Coding Academy
    link: https://www.summercodingacademy.hsa.net/
    logo_relative_url: /summercodingacademy.png
  - name: StickerYou
    link: https://www.stickeryou.com
    logo_relative_url: /stickeryou.png
  - name: Papa John's
    link: https://www.papajohns.com
    logo_relative_url: /papa-johns.jpg
  - name: Sticker Mule
    link: https://www.stickermule.com
    logo_relative_url: /stickermule.png
  - name: Radix
    link: https://www.get.tech
    logo_relative_url: /radix.png